[phases.setup]
    nixPkgs = ['bun']
    nixLibs = ['openssl']

[phases.install]
    cmds = ['bun install --include=optional sharp']

[phases.build]
    cmds = ['bunx prisma generate', 
        'bunx prisma db push', 
        'bun build --target=bun ./src/index.ts --outdir ./build']

[start]
    cmd = 'bun run src/index.ts'